addons:
  ssh_known_hosts: $deploy_host

before_install:
- openssl aes-256-cbc -K $encrypted_210275373e1a_key -iv $encrypted_210275373e1a_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: bash scripts/deploy.sh
  on:
    all_branches: true
