language: generic
addons:
  ssh_known_hosts:
  - "$DEPLOY_SERVER_HOST"
  - "$DEPLOY_SERVER_HOST_IP"
before_install:
- openssl aes-256-cbc -K $encrypted_210275373e1a_key -iv $encrypted_210275373e1a_iv
  -in deploy/deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: bash deploy/deploy.sh
  on:
    branch: master
notifications:
  slack:
    secure: dA8NxFj20C5ABzLtfRkqV2+a4Zf8RrmJAVug5/50dAnU5wRZnrsIXN+62yVyaZuzHwC1Sp/9BrrEe/lLnQ9abpK2A/nsJTr44RO6Fw8N2czsLKse/uZv7fo2f+cRG7fu7tNhSjveJqljxqu9vfziqxht5XzFKJpfygmcmcBkp+B7FMw0QfFBirz8rM47cD6wci5Oc8184Wvr4EeXhOC6aPsWVe3dI1VPoSOhrwC8yEq5Zr01gnZUO4sGDTkaYyxXCHZ4kgaMnrTm25dZVonPG195AV9rDA+idEqXlygEpEA7aa6+kDkDoApRAaiNyJJJwenVOuJqKQCvAGnXXBdIiN6Kany/M2rYyTnjljikZiC4Qp23CgKcPdqHNJaa10ifbezp0KOAGxF/0LCq1b7Q+7RpzLXD7nKGLu4D6UNPJZLNZJ9WIA5AwjDmKRCCBHkI99Qnor5fKSX11E4gqASYxvFKYThIEAdzf04gvlCqJ7ayBUF1mdL6hq+sIHe6vBwlK8EjSaWNlgqpKXnoEfx1WZyZVZ1vOQ7Tg53RqMRZZObN+t77aKH5QicRp8dva1GDPdsqBftlWWyzTCH4hD0nRhpfWTWd3pYxw8D62/Tv+m5o5ER7ZKiyG0DvTlNWnHEsf451y8Lj1NpGumA2J0YsyybP0F5BAVpMOpTl2ynu5L8=
